language: java
script:
- ./gradlew jar distZip
notifications:
  hipchat:
    rooms:
      secure: a+Z+kNPc7cHUmQyVZZW9PBL5TYoDOGLZvjvbJeih4Z3hkK1jWkI1Vb7hy76yoMtGXhutgswmpn8GES4MbLC8kdyy8E+yDCPcl9f+axFE9mPFGpUSbl4pEjjeQ7+uH2Z60WOINX1SQ0V1pdN1kD/J+2P6ykKR0G17TIgH7JuRwWxM+G8UWAPx4bykKIpNMn9opxGJ4qr/cPZF15Wiz18XcGlhjDeAym2ntjB3ZnTi3Wv8kCkcG4SdIpMg7BJszq941NOkgZX+1rHzJhliIT6N3g2dhxlLiPBPsvBSARD0Q4lStriR1HwupBPNVYwPqIprVlxhduqd2L+ejt4p/Av+RfU4w4PIQ54Pa8hMEjp1oNGk2QKEEhaVQlp0o4+9yO1qcti6iqaKNC9AIAB8puF/X6Rno1TyVLVxTvHe0lFg/t4m4Vy8abUP/gp0dyy5mFIGbuivr4MS6mO8CsKVtHiLCqv5A0jyRhktXU1vCGa6pbwQZciABFWGhht1g1nal6/FrkgGbEgAtUOfAfnYpaZ339H9l9HtkMK8puHbqlP22JB2x6ZEUM/GiroVfhGrgbNK5cFCMNenK/Wdg1oiJwNW3kgqxjddPsmlnb1SGdfUXyIWxlD1qpV36WdMH9REbrYb6O6RystTlA8btRwrptBG6Iiu90PhjRM0BVPV9QAPfn8=
deploy:
  provider: releases
  api_key:
    secure: F7pVe0mrHlEi7oQeU/J0T0UWsA3PMuQCMmAN7o/JR8mDEjD255y37W+L6UMPiTQVaWSY6nMTAVcuubLxWmBCFEjDQkM82TBVawLVytc7Z7JmIDzq1bOypcvi/s+zGMzktPGzzEXbm3ClwY2gSWRozTmKszBFUexZgvv06CE6fhp0aw/8G9G1T+FG73VnyWzYfRJ9rfdItEi6XL1F/uFU/atW7ilJCHAHPcigu8Upb+ZuAB+ZB/WlDbRl60B4mCwea497tXaoSX6kW4LpmnPMhBNBnSvxZ86HmWTQOpMZr7fJy4YPN7btgtd2KsJz37WQoK0XbYRROfaZdV1gckWAnrnuEOK8/2lsqGV1pry4Z6p7eyAtLP+syq6o0VB3sM4s3x8Gc20geX8+3ts64qqzaR3QqR6IGMrFQTCp5IgbyezU3y/6cxCbtqloQMss13WIhgw6mrzp3dpjcxCNSVXn8XMUO9MRb/FJsWQbV+GAErnk5WScOQRtCVKMn0/aPTb7umRdD20AkQt6971dzO+SFCMRa/7ka1lQad1pPyNKVdhB45U7QsyZ9pNCLKA93UnEzwjVuKm7hrcbVE6YKNW7yrEU7Yk/JuHooh3f+6U8bdZOVEl5bBQRqj3if4XwdpEXx3enRrtNAMeZazofI5a/wIevVtrcX7tqaGM2wuSn8o4=
  file: build/distributions/xlr-perforce-changelist-trigger-plugin-1.0.2.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-perforce-changelist-trigger-plugin

